#! /bin/sh
# generate multilooked geometry files for ISCE/stripmapStack product
# Author: Zhang Yunjun, 2019-03-10

alooks=14
rlooks=4
in_dir='./merged/geom_master'
out_dir='./geom_master'

#geom_master folder
if [ ! -d ${out_dir} ]; then
    echo 'create '${out_dir}
    mkdir ${out_dir}
fi

#multilook geometry files
for fbase in hgt incLocal lat lon los shadowMask
do
    fname=${fbase}'.rdr'
    echo 'multilook '${fname}
    looks.py -a ${alooks} -r ${rlooks} -i ${in_dir}/${fname} -o ${out_dir}/${fname}
    cp ${in_dir}/${fname}.xml ${out_dir}/${fname}.full.xml
    cp ${in_dir}/${fname}.vrt ${out_dir}/${fname}.full.vrt
done

